version: '3'
services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm start
    environment:
      - PORT=3001
    ports:
      - 3001:3001
    volumes:
      - ./dist:/var/www/api/dist:consistent

